mysql: &mysql
  adapter: mysql2
  username: root
  password:
  database: invoicer_<%= ENV['RAILS_ENV'] %>

defaults: &default
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "mysql" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults